version: '3'
services:
  server:
    container_name: ppp_server
    build:
      dockerfile: config/docker/server.Dockerfile
      context: .
      target: dev
    ports:
      - '5050:5050'
    volumes:
      - .:/www
    depends_on:
      - db
    links:
      - db
    environment:
      DB_NAME: &db peter_park_plate_db
      DB_USER: &dbUser ppddb_user
      DB_PASS: &dbPassword ppddb_user_password
      DB_HOST: db

  db:
    container_name: db
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: *db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: *dbUser
      MYSQL_PASSWORD: *dbPassword
    ports:
      - '3306:3306'
    volumes:
      - ./config/sql:/docker-entrypoint-initdb.d/:ro
